# Generated by Django 3.0.5 on 2020-05-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
                ("exchange", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "symbol",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("display_symbol", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Gap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gaps",
                        to="equities.Company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target", models.IntegerField()),
                ("threshold", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="equities.Company",
                    ),
                ),
            ],
        ),
    ]
