# Generated by Django 3.0.5 on 2020-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gap',
            name='next_timestamp',
        ),
        migrations.AddField(
            model_name='gap',
            name='volume_above_average',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gap',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gap',
            name='next_open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gap',
            name='next_volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gap',
            name='percent',
            field=models.FloatField(),
        ),
    ]
